version: '3'
services:
  speedtest:
    container_name: speedtestv2
    image: 155417270b8d 
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ~/Docker/speedtest-combined/docker-speedtest-analyser/data:/var/www/html/data
    ports:
      - 8088:80
      - 4344:443
    environment:
      - CRONJOB_ITERATION=15
      - SPEEDTEST_COMMAND=fast --upload
